### PR TITLE
Fix nested waitUntils

### LINKED ISSUE #7: Nested `waitUntil` not correctly awaited
Due to this line I believe nested `waitUntil`s are not correctly awaited:

https://github.com/evanderkoogh/otel-cf-workers/blob/9b40f78e8a84b34fa31e8db1d26013c0844f74ed/src/instrumentation/common.ts#L22-L24

It's exactly the same issue as here:
https://github.com/cloudflare/miniflare/issues/605

I'll open a PR implementing [this code](https://github.com/bubblydoo/wait-until-generalized/blob/main/src/all-settled-mutable.ts).

### PR DESCRIPTION
**Pull request by hansottowirtz**
Fixes #7.

I also believe `Promise.allSettled` is more appropriate than `Promise.all` here, because it can't throw.

### CODE REVIEW

**Review by evanderkoogh — CHANGES_REQUESTED** [review]
This certainly works, but there is a way to slightly clean it up with the method implementation:

```typescript
	let values: PromiseSettledResult<unknown>[]
	// when the length of the array changes, there has been a nested call to waitUntil
	// and we should await the promises again
	do {
		values = await Promise.allSettled(promises)
	} while (values.length !== promises.length)
	return values
	```
	
The great thing about a `do..while` loop is that it is guaranteed to execute at least once, which eliminates the need for the intermediate `len` value and makes the code more explicit.

Just to be clear, I am extremely grateful for not just the bug report, but also the PR, which is why I am requesting changes, so that you can get full credit for it.
But I am also very happy to merge and then change it myself. Let me know.

**Comment by hansottowirtz** [comment]
Great idea! I've pushed the changes. No worries about the credit :)

**Comment by evanderkoogh** [comment]
Looks great :)

**Comment by michaeldoron59** [comment]
Hey guys, is it only me who still suffer this issue?

**Pull request merged**
