### PR TITLE
specify output dir in dist

### LINKED ISSUE #162: import / resolution error
Installed the package via NPM intending to implement baselime + otel + cloudflare workers per https://baselime.io/docs/sending-data/platforms/cloudflare/traces/

The entrypoint in package.json doesn't match up to the output dir in /dist. As you can see, the src dir is being inferred as the outdir (https://www.typescriptlang.org/tsconfig/#rootDir)

```
➜  otel-cf-workers git:(b38873a) ✗ tree -L 2 ./dist
./dist
├── cjs
│   ├── package.json
│   └── src
└── esm
    ├── package.json
    └── src
```

```
✘ [ERROR] Could not resolve "@microlabs/otel-cf-workers"

    src/index.ts:4:44:
      4 │ ... { instrument, ResolveConfigFn } from '@microlabs/otel-cf-workers';
        ╵                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The module "./dist/esm/index.js" was not found on the file system:

    node_modules/@microlabs/otel-cf-workers/package.json:11:15:
      11 │         "default": "./dist/esm/index.js"
         ╵                    ~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@microlabs/otel-cf-workers" as external to exclude it from the bundle, which will remove this error.
```

running on `node v20.16.0`

deps
```
├── @baselime/edge-logger@0.3.2
├── @cloudflare/workers-types@4.20240903.0
├── @microlabs/otel-cf-workers@1.0.0-rc.46
├── @opentelemetry/api@1.9.0
├── @tsndr/cloudflare-worker-jwt@2.5.3
├── openai@4.55.0
├── typescript@5.4.4
├── web-auth-library@1.0.3
├── workers-qb@1.4.1
├── wrangler@3.74.0
└── zod@3.23.8
```

### PR DESCRIPTION
**Pull request by pkarl**
updated tsconfig for esm + cjs to explicitly set output dirs; added package info embed to avoid package.json path resolution issue

Fixes #162 

**What this PR solves / how to test:**

- specify output dirs in tsconfig for esm + cjs
- use build-time generated js file for name + version instead of package.json resolution

testing env:

- node v20.16.0
- typescript@5.4.4

to test:

1. create a cloudflare worker via `npm create cloudflare@latest -- my-first-worker`
2. `cd my-first-worker`
3. confirm worker runs with `npm run dev`
4. install latest otel cf workers with `npm i @microlabs/otel-cf-workers`
5. run `npm run dev`, should see error per #162

### CODE REVIEW

**Comment by parisholley** [comment]
just ran into this :) @evanderkoogh any chance of a merge?

**Comment by jahands** [comment]
Why is the `dist` directory committed in this PR?

**Comment by pkarl** [comment]
Oh whoops, that was for my local installation/deploy for a duct tape
solution, my b

**Comment by pkarl** [comment]
looks like @evanderkoogh modded to solve, closing this PR

**Comment by oldbettie** [comment]
is this fixed? It fails I am not sure where to go from here

**Comment by pkarl** [comment]
no it appears to still be borked.

**Comment by pkarl** [comment]
attn @evanderkoogh this still needs to be addressed. See the tsconfig changes in this PR. If you want I can re-PR with your versions changes and remove the whole dist mess from this

**Pull request closed without merging**
